### ISSUE TITLE
Problems starting and getting value in double quotes

### ISSUE THREAD

**Issue by pniedermeyer** [IndexXuan/vite-plugin-env-compatible#2]
Hey, first of all thanks for that amazing module. It helps a lot. But to get it running i had to modify it a bit.

I got 
`error when starting dev server:
TypeError: Cannot destructure property 'mode' of 'undefined' as it is undefined.
    at Object.config (C:\Users\....\node_modules\vite-plugin-env-compatible\dist\index.js:200:21)`

I solved it by removing the curly brackets around the mode.

Another Problem i encountered is that the values are always in double quotes. I think its because of the JSON.stringify. Is there a special reason therefore or can it be removed?

Line 214: `myDefine['${options.mountedPath}.${key}'] = JSON.stringify(value);`

If desired, i can provide a PR

**Comment by IndexXuan** [comment]
https://vitejs.dev/guide/api-plugin.html#config

https://vitejs.dev/config/#define
 
which vite version you use. mode should be here and define must be use stringify.
maybe we can make special prefix to avoid stringify, like origin:

**Comment by pniedermeyer** [comment]
It seems like i had an old Version of vite. It was 2.0.0-beta.66. After an Update it all worked fine. Also the double quotes aren't a problem anymore. The values are as expected.

Thanks a lot for your help

**Comment by IndexXuan** [comment]
I will give some check within plugin. thanks for feedback.
