### ISSUE TITLE
Plugin is no longer needed since Vite 2.5.2

### ISSUE THREAD

**Issue by AgainPsychoX** [IndexXuan/vite-plugin-env-compatible#7]
See
* https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#252-2021-08-31
* https://vitejs.dev/config/index.html#envprefix

Good news, should be added to README for sure.

Meanwhile, the plugin should stay up for old projects I guess (maybe archaized?).

**Comment by IndexXuan** [comment]
vite never load env var to process.env and it is just define for client code. it support now?

**Comment by IndexXuan** [comment]
https://github.com/vitejs/vite/blob/689a2c8cbab0887dba0994dd0e9dc5515ab9d461/packages/vite/src/node/config.ts#L994

we do need this. like we have PROXY_TARGET in .env.development and some plugin need know it by real process.env.Xxx not client define process.env or import.meta.env

**Comment by IndexXuan** [comment]
Also Imake this plugin most for vue-cli-plugin-vite for compat.
