### ISSUE TITLE
Env variables accessed using `process.env` are not substituted in production build

### ISSUE THREAD

**Issue by harrygr** [IndexXuan/vite-plugin-env-compatible#8]
I'm using this plugin to allow accessing env vars via `process.env` in my codebase (rather than `import.meta.env`) to allow for compatibility with my testing suite.

It works well in dev mode (via `vite`), however when I run the production build `vite build` the resulting bundle does not have the env variables that are accessed via `process.env` substituted and they are instead set to an empty string.

**Comment by david-cord** [comment]
Did you find a way to resolve this @harrygr , it appears this plugin only achieves half of what we really need.

Many thanks in advance

**Comment by IndexXuan** [comment]
will check it. env inject with vite-plugin config hook, is it not apply in build mode?

**Comment by david-cord** [comment]
That's right, as it stands it seems this plugin writes to process.env in dev mode (esbuild) but not in build mode (rollup).  You'll get `process is undefined` for example when viewing the hosted prod build.

**Comment by harrygr** [comment]
@david-cord I actually ended up using the [vite-plugin-environment][1] package instead (although I'm sure this package should work just as well).

See the similar issue on the repo that eventually led to a working solution: https://github.com/ElMassimo/vite-plugin-environment/issues/1

In short, I basically use `EnvironmentPlugin('all', { prefix: 'VITE_' })` in my vite config that means my env variables are available on `process.env`

[1]:https://github.com/ElMassimo/vite-plugin-environment

**Comment by david-cord** [comment]
Thank you for your response @harrygr , appreciated.

In my instance, there was a helper function that was querying properties of the process object with a dynamic `process.env[key]`. I wasn't aware in prod build this became string replaced so only complete absolute references get swapped out and work!

Thanks again both!
